"""
LangGraph state schema for the multi-agent QA flow.

This state object moves through the three-agent pipeline:
1. Retrieval Agent
2. Summarization Agent
3. Verification Agent
"""

from typing import TypedDict, Dict, Any


class QAState(TypedDict):
    """
    Shared state passed between LangGraph nodes.

    Fields
    ------
    question:
        The user's original question.

    context:
        Text context retrieved from the vector database
        (A/L Biology Grade 12 & 13 resource books).

    citations:
        Metadata for retrieved chunks such as
        source book, chapter, page number.

    draft_answer:
        Initial answer generated by the summarization agent.

    answer:
        Final verified answer produced by the verification agent.
    """

    question: str

    context: str

    citations: Dict[str, Dict[str, Any]]

    draft_answer: str

    answer: str